// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	dto "schedule_table/internal/model/dto"

	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// CalendarsHandler is an autogenerated mock type for the CalendarsHandler type
type CalendarsHandler struct {
	mock.Mock
}

// GetMyCalendar provides a mock function with given fields: c
func (_m *CalendarsHandler) GetMyCalendar(c *gin.Context) (*[]dto.ResponseCalendar, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetMyCalendar")
	}

	var r0 *[]dto.ResponseCalendar
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context) (*[]dto.ResponseCalendar, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context) *[]dto.ResponseCalendar); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]dto.ResponseCalendar)
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCalendarsHandler creates a new instance of CalendarsHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCalendarsHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *CalendarsHandler {
	mock := &CalendarsHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
