// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Id is an autogenerated mock type for the Id type
type Id struct {
	mock.Mock
}

// NewId creates a new instance of Id. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewId(t interface {
	mock.TestingT
	Cleanup(func())
}) *Id {
	mock := &Id{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
