// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	dao "schedule_table/internal/model/dao"

	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// LeaveHandler is an autogenerated mock type for the LeaveHandler type
type LeaveHandler struct {
	mock.Mock
}

// CreateNewLeave provides a mock function with given fields: c
func (_m *LeaveHandler) CreateNewLeave(c *gin.Context) (*dao.Leaves, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewLeave")
	}

	var r0 *dao.Leaves
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context) (*dao.Leaves, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context) *dao.Leaves); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Leaves)
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: c
func (_m *LeaveHandler) Delete(c *gin.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gin.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLeave provides a mock function with given fields: c
func (_m *LeaveHandler) GetLeave(c *gin.Context) (*[]dao.Leaves, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetLeave")
	}

	var r0 *[]dao.Leaves
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context) (*[]dao.Leaves, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context) *[]dao.Leaves); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]dao.Leaves)
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLeaveHandler creates a new instance of LeaveHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLeaveHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *LeaveHandler {
	mock := &LeaveHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
