// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	dto "schedule_table/internal/model/dto"

	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// ScheduleHandler is an autogenerated mock type for the ScheduleHandler type
type ScheduleHandler struct {
	mock.Mock
}

// CreateNewSchedule provides a mock function with given fields: c
func (_m *ScheduleHandler) CreateNewSchedule(c *gin.Context) (*dto.ResponseSchedule, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewSchedule")
	}

	var r0 *dto.ResponseSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context) (*dto.ResponseSchedule, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context) *dto.ResponseSchedule); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ResponseSchedule)
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteSchedule provides a mock function with given fields: c
func (_m *ScheduleHandler) DeleteSchedule(c *gin.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSchedule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gin.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetScheduleId provides a mock function with given fields: c
func (_m *ScheduleHandler) GetScheduleId(c *gin.Context) (*dto.ResponseSchedule, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetScheduleId")
	}

	var r0 *dto.ResponseSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context) (*dto.ResponseSchedule, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context) *dto.ResponseSchedule); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ResponseSchedule)
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSchedules provides a mock function with given fields: c
func (_m *ScheduleHandler) GetSchedules(c *gin.Context) (*[]dto.ResponseSchedule, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetSchedules")
	}

	var r0 *[]dto.ResponseSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context) (*[]dto.ResponseSchedule, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context) *[]dto.ResponseSchedule); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]dto.ResponseSchedule)
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateSchedule provides a mock function with given fields: c
func (_m *ScheduleHandler) UpdateSchedule(c *gin.Context) (*dto.ResponseSchedule, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSchedule")
	}

	var r0 *dto.ResponseSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context) (*dto.ResponseSchedule, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context) *dto.ResponseSchedule); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ResponseSchedule)
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewScheduleHandler creates a new instance of ScheduleHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScheduleHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScheduleHandler {
	mock := &ScheduleHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
