// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	dao "schedule_table/internal/model/dao"
	dto "schedule_table/internal/model/dto"

	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// TasksHandler is an autogenerated mock type for the TasksHandler type
type TasksHandler struct {
	mock.Mock
}

// GetTasks provides a mock function with given fields: c
func (_m *TasksHandler) GetTasks(c *gin.Context) (*[]dto.ResponseTask, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetTasks")
	}

	var r0 *[]dto.ResponseTask
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context) (*[]dto.ResponseTask, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context) *[]dto.ResponseTask); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]dto.ResponseTask)
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReserveMember provides a mock function with given fields: c
func (_m *TasksHandler) ReserveMember(c *gin.Context) (*dao.Tasks, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for ReserveMember")
	}

	var r0 *dao.Tasks
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context) (*dao.Tasks, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context) *dao.Tasks); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Tasks)
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTasksHandler creates a new instance of TasksHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTasksHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *TasksHandler {
	mock := &TasksHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
