// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"schedule_table/internal/database"
	"schedule_table/internal/handler"
	"schedule_table/internal/repository"
	"schedule_table/internal/router"
	"schedule_table/internal/service"
)

// Injectors from wire.go:

func Injector() *router.Handlers {
	db := database.ConnectPostgresql()
	calendarRepository := repository.NewCalendarRepository(db)
	schedulesRepository := repository.NewSchedulesRepository(db)
	calendarsHandler := handler.NewCalendarsHandler(calendarRepository, schedulesRepository)
	jwtService := service.NewJWTAuthService()
	userRepository := repository.NewUserRepository(db)
	authHandler := handler.NewAuthHandler(jwtService, userRepository)
	handlers := &router.Handlers{
		Calendar: calendarsHandler,
		Auth:     authHandler,
	}
	return handlers
}

// wire.go:

var (
	calendarSet = wire.NewSet(handler.NewCalendarsHandler, repository.NewCalendarRepository)

	scheduleSet = wire.NewSet(repository.NewSchedulesRepository)

	authSet = wire.NewSet(handler.NewAuthHandler, service.NewJWTAuthService, repository.NewUserRepository)
)
